### ISSUE TITLE
Bug `markdown-it-shikiji` highlightLines is overwritten

### ISSUE THREAD

**Issue by hunghg255** [antfu/shikiji#40] opened 2023-12-13 01:56 UTC
### Describe the bug

- highlightLines is overwritten with others block

## Result
<img width="400" alt="Screenshot 2023-12-13 at 08 47 14" src="https://github.com/antfu/shikiji/assets/42096908/24692fb1-97dc-4a66-aa68-bb9da7bad96a">

## My markdown
<img width="407" alt="Screenshot 2023-12-13 at 08 50 31" src="https://github.com/antfu/shikiji/assets/42096908/aa81807d-386d-490b-ad3e-49e771b0c5e2">

## My code
```ts
import MarkdownIt from 'markdown-it'
import Shikiji from 'markdown-it-shikiji'

const md = MarkdownIt()

md.use(await Shikiji({
  themes: {
    light: 'vitesse-light',
    dark: 'vitesse-dark',
  },
 transformers: [
      // transformerNotationDiff(),
      transformerTwoSlash({
        renderer: rendererRich, // <--
      }),
    ],
}))
  ```
  
  

### Reproduction

highlightLines is overwritten with others block

### System Info

```Shell
System:
    OS: macOS 13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 11.10 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.0/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 8.10.0 - ~/.nvm/versions/node/v18.18.0/bin/pnpm
    bun: 1.0.11 - ~/.bun/bin/bun
    Watchman: 2023.09.25.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 120.0.6099.71
    Safari: 16.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-12-13 08:28
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by hunghg255** [comment] 2023-12-13 09:29
@antfu I created a project on Stackblitz, can you check this
https://stackblitz.com/edit/vitejs-vite-94vbmz?file=src%2Fmain.ts

**Closed** 2023-12-13 13:55 UTC
