### ISSUE TITLE
Error: `runSync` finished async. Use `run` instead

### ISSUE THREAD

**Issue by arunavo4** [antfu/shikiji#22] opened 2023-10-07 01:32 UTC
### Describe the bug

This project does not work with React-Markdown as it uses async call.
```
<ReactMarkdown
      remarkPlugins={[
        remarkGfm,
        [remarkMath, { singleDollarTextMath: true }],
      ]}
      rehypePlugins={[
        rehypeKatex,
        [
          rehypeShikiji,
          {
            themes: {
              light: "vitesse-light",
              dark: "vitesse-dark",
            },
          },
        ],
      ]}
      components={{
        code(props) {
          const { children, className, node, ...rest } = props;
          const match = /language-(\w+)/.exec(className || "");
          const lang = match && match[1];
          return match ? (
            <CodeBlock lang={lang || "text"} codeChildren={children} />
          ) : (
            <code {...rest} className={className}>
              {children}
            </code>
          );
        },
      }}
    >
      {message.content}
 </ReactMarkdown>
```
Error: `runSync` finished async. Use `run` instead

### Reproduction

Using it with Nextjs Client Side and React-Markdown.

### System Info

```Shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 145.05 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    pnpm: 7.2.1 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 17.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-10-07 06:15
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-10-07 06:15 UTC

**Comment by antfu** [comment] 2023-10-18 11:05
> `runSync`

rehypeShikiji is an async plugin, you might need to configure your ReactMarkdown to run async somehow.

> module has no exports

It seems to be a Next.js issue: https://github.com/antfu/shikiji/issues/13#issuecomment-1749588964

---

I think either issue are not related to shikiji itself.
